### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Misiu** [zsarnett/Lit-Grid-Layout#13]
When going to [the demo page](https://lit-grid-layout.netlify.app/) I get this error:

> Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".

Checked on Chrome 84.0.4147.105 (Win10)

**Comment by zsarnett** [comment]
Currently working on that. I stopped using roll-up so importing it into the browser directly doesn't work. Just got it added to cdnjs and will update the demo to use that link

**Comment by zsarnett** [comment]
https://lit-grid-layout.netlify.app/

**Comment by Misiu** [comment]
@zsarnett now everything works perfectly!

**Comment by arulselvan** [comment]
@zsarnett  - the demo URL again seems like not working, but your work was awesome, thanks!
